c: handle clang plugins better.
This runs the analysis in a distributed fashion for me, but it causes errors
because the plugin fails to distinguish whether something is in a third-party
path or not, presumably.

So you get errors like:

```
0:12.92 /home/emilio/src/moz/gecko-2/security/sandbox/chromium/base/strings/safe_sprintf.h:177:3: error: bad implicit conversion constructor for 'Arg'
0:12.92   Arg(unsigned long long j) : type(UINT) {
0:12.92   ^
0:12.92 /home/emilio/src/moz/gecko-2/security/sandbox/chromium/base/strings/safe_sprintf.h:177:3: note: consider adding the explicit keyword to the constructor
0:12.92   Arg(unsigned long long j) : type(UINT) {
0:12.92   ^
0:12.92   explicit
0:12.92 /home/emilio/src/moz/gecko-2/security/sandbox/chromium/base/strings/safe_sprintf.h:183:3: error: bad implicit conversion constructor for 'Arg'
0:12.92   Arg(const char* s) : str(s), type(STRING) { }
0:12.92   ^
0:12.92 /home/emilio/src/moz/gecko-2/security/sandbox/chromium/base/strings/safe_sprintf.h:183:3: note: consider adding the explicit keyword to the constructor
0:12.92   Arg(const char* s) : str(s), type(STRING) { }
```

Even though security/sandbox/chromium is in a third-party path. This is a bug in
the clang plugin which doesn't handle line directives, and I have a patch for
it.

Fixes #562.